[package]
name = "hyperpack"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
regex = "1"
minify = "1.3.0"
rayon = "1.7"
serde = "1.0.209"
serde_json = "1.0.127"
indicatif = "0.17"
clap = "4.1"
log = "0.4"
simple_logger = "5.0.0"